[DIVISIONDATA]
Split=2
Block=2
Score=StepG
Min=1
Max=1

##################################################
Split=2
Block=3
Score=StepG
Min=2
Max=2

##################################################
Split=2
Block=4
Score=StepG
Min=3
Max=3

##################################################
